"""Add matches table for reconciliation

Revision ID: 6e12043bf5df
Revises: ef9edfa7b2fa
Create Date: 2026-01-20 17:42:01.290779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e12043bf5df'
down_revision: Union[str, None] = 'ef9edfa7b2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("status IN ('proposed', 'confirmed', 'rejected')", name='ck_matches_status_valid'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_matches_score_range'),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_bank_transaction_id'), 'matches', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_matches_invoice_id'), 'matches', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index('ix_matches_tenant_id', 'matches', ['tenant_id'], unique=False)
    op.create_index('ix_matches_tenant_invoice', 'matches', ['tenant_id', 'invoice_id'], unique=False)
    op.create_index('ix_matches_tenant_status_score', 'matches', ['tenant_id', 'status', 'score'], unique=False)
    op.create_index('ix_matches_tenant_transaction', 'matches', ['tenant_id', 'bank_transaction_id'], unique=False)
    op.create_index('ix_matches_unique_pair', 'matches', ['tenant_id', 'invoice_id', 'bank_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matches_unique_pair', table_name='matches')
    op.drop_index('ix_matches_tenant_transaction', table_name='matches')
    op.drop_index('ix_matches_tenant_status_score', table_name='matches')
    op.drop_index('ix_matches_tenant_invoice', table_name='matches')
    op.drop_index('ix_matches_tenant_id', table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_invoice_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_bank_transaction_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
