"""Add tenants table

Revision ID: 9517be91c6de
Revises: 
Create Date: 2026-01-20 15:08:49.512079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9517be91c6de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idempotency_expires_at', 'idempotency_records', ['expires_at'], unique=False)
    op.create_index('ix_idempotency_lookup', 'idempotency_records', ['tenant_id', 'idempotency_key'], unique=False)
    op.create_index('ix_idempotency_unique_per_tenant', 'idempotency_records', ['idempotency_key', 'tenant_id'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenants_is_active', 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_index('ix_tenants_name_active', 'tenants', ['name', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_name_active', table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index('ix_tenants_is_active', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_idempotency_unique_per_tenant', table_name='idempotency_records')
    op.drop_index('ix_idempotency_lookup', table_name='idempotency_records')
    op.drop_index('ix_idempotency_expires_at', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
