"""add_bank_transactions_table

Revision ID: ef9edfa7b2fa
Revises: 2c188d8e250b
Create Date: 2026-01-20 16:27:07.029828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9edfa7b2fa'
down_revision: Union[str, None] = '2c188d8e250b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('amount != 0', name='ck_bank_tx_amount_nonzero'),
    sa.CheckConstraint('length(currency) = 3', name='ck_bank_tx_currency_len'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_transactions_posted_at', 'bank_transactions', ['posted_at'], unique=False)
    op.create_index('ix_bank_transactions_tenant_external', 'bank_transactions', ['tenant_id', 'external_id'], unique=True)
    op.create_index(op.f('ix_bank_transactions_tenant_id'), 'bank_transactions', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_index('ix_tenants_name', 'tenants', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_name', table_name='tenants')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=1)
    op.drop_index(op.f('ix_bank_transactions_tenant_id'), table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_tenant_external', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_posted_at', table_name='bank_transactions')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
